/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "bruch_tests.ts" instead.
 */

#include <check.h>

#line 1 "bruch_tests.ts"
#include "bruch.h"

START_TEST(product_kuerzen)
{
#line 4
    bruch a = {.zaehler = 10, .nenner = 5};
    bruch b = {.zaehler = 2, .nenner = 3};
    bruch c = product(a, b);
    ck_assert_int_eq(c.zaehler, 4);
    ck_assert_int_eq(c.nenner, 3);

}
END_TEST

START_TEST(product_nicht_kuerzen)
{
#line 11
    bruch a = {.zaehler = 3, .nenner = 5};
    bruch b = {.zaehler = 7, .nenner = 11};
    bruch c = product(a, b);
    ck_assert_int_eq(c.nenner, a.nenner * b.nenner);
    ck_assert_int_eq(c.zaehler, a.zaehler * b.zaehler);

}
END_TEST

START_TEST(kuerze_einfaches_vielfaches)
{
#line 18
    bruch a = {.zaehler = 15, .nenner = 5};
    kuerze(&a);
    ck_assert_int_eq(a.nenner, 1);
    ck_assert_int_eq(a.zaehler, 3);

}
END_TEST

START_TEST(kuerze_gemeinsame_primfaktoren)
{
#line 24
    bruch a = {.zaehler = 6, .nenner = 14};
    kuerze(&a);
    ck_assert_int_eq(a.nenner, 7);
    ck_assert_int_eq(a.zaehler, 3);

}
END_TEST

START_TEST(print_einhalb)
{
#line 30
    bruch a = {.zaehler = 10, .nenner = 20};
    char ausgabe[100];
    print(a, ausgabe);
    // Nur die ersten 3 Zeichen vergleichen
    ausgabe[3] = '\0';
    ck_assert_str_eq(ausgabe, "0.5");

}
END_TEST

START_TEST(print_minus_drittel)
{
#line 38
    bruch a = {.zaehler = 3, .nenner = -9};
    char ausgabe[100];
    print(a, ausgabe);
    // Nur die ersten 6 Zeichen vergleichen
    ausgabe[6] = '\0';
    ck_assert_str_eq(ausgabe, "-0.333");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, product_kuerzen);
    tcase_add_test(tc1_1, product_nicht_kuerzen);
    tcase_add_test(tc1_1, kuerze_einfaches_vielfaches);
    tcase_add_test(tc1_1, kuerze_gemeinsame_primfaktoren);
    tcase_add_test(tc1_1, print_einhalb);
    tcase_add_test(tc1_1, print_minus_drittel);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
