/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "urls_finden_tests.ts" instead.
 */

#include <check.h>

#line 1 "urls_finden_tests.ts"
#include "urls_finden.h"

void urls_testen(char richtige_urls[10][150], int richtige_anzahl, char *text){
    char urls[10][150];
    int anzahl = urls_finden(urls, text);

    ck_assert_int_eq(anzahl, richtige_anzahl);

    for (int i = 0; i < anzahl; i++){
        ck_assert_str_eq(urls[i], richtige_urls[i]);
    }
}

START_TEST(keine_urls)
{
#line 15
    char *text = "Hello, World!";
    char urls[10][150];
    urls_testen(urls, 0, text);

}
END_TEST

START_TEST(beispiel)
{
#line 20
    char *text = "https://www.example.com";
    char urls[10][150] = {"https://www.example.com"};
    urls_testen(urls, 1, text);

}
END_TEST

START_TEST(beispiel_in_text)
{
#line 25
    char *text = "Die https URL lautet zum Beispiel:https://www.example.com <----";
    char urls[10][150] = {"https://www.example.com"};
    urls_testen(urls, 1, text);

}
END_TEST

START_TEST(alle_drei_formate)
{
#line 30
    char *text = "https://www.example.com www.example.com http://example.com";
    char urls[10][150] = {"https://www.example.com", "www.example.com", "http://example.com"};
    urls_testen(urls, 3, text);

}
END_TEST

START_TEST(verbotene_sonderzeichen)
{
#line 35
    char *text = "}www.example.com|www.example.com`www.example.com\\www.example.com{";
    char urls[10][150] = {"www.example.com", "www.example.com", "www.example.com", "www.example.com"};
    urls_testen(urls, 4, text);

}
END_TEST

START_TEST(erlaubte_sonderzeichen)
{
#line 40
    char *text = "https://example.com:80/@foo/bar.html?q=1;s=2&t=3!#$%~'(a.s-d_f~g),([12+3*4])";
    char urls[10][150] = {
        "https://example.com:80/@foo/bar.html?q=1;s=2&t=3!#$%~'(a.s-d_f~g),([12+3*4])"
    };
    urls_testen(urls, 1, text);

}
END_TEST

START_TEST(www)
{
#line 47
    char *text = "wwwachnedochnicht";
    char urls[10][150];
    urls_testen(urls, 0, text);

}
END_TEST

START_TEST(nicht_ganz_https)
{
#line 52
    char *text = "https:/ach kein Bock mehr";
    char urls[10][150];
    urls_testen(urls, 0, text);

}
END_TEST

START_TEST(verschiedene_urls)
{
#line 57
    char *text =
        "Das beste Video: https://www.youtube.com/watch?v=dQw4w9WgXcQ "
        "Ein Link zum ILIAS: https://ilias.hhu.de/ilias.php?ref_id=1&cmdClass=ilrepositorygui&cmdNode=va&baseClass=ilrepositorygui ,"
        "Wikipedia-Eintrag zur Programmiersprache C https://en.wikipedia.org/wiki/C_(programming_language) "
        "Microsoft https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DVhh_GeBPOhs&format=json "
        "Klackernde Tastaturen https://i.imgur.com/pbqiLgY.gif "
        "Schlecht kommentierter Code https://raw.githubusercontent.com/ProjectDock/programming-memes/main/src/MEMES/images/I-am-Harshdeep/meme.png "
        "Schlecht kommentierter Code 2 https://abstrusegoose.com/strips/you_down_wit_OPC-yeah_you_know_me.png "
        "https://i.imgur.com/5DlqfCl.jpg Sonderfaelle "
        "C vs C++ https://devhumor.com/content/uploads/images/December2016/c++-c-class.jpg "
        "Hyperlink https://i.imgur.com/cV9m29E.png "
        "Denkt daran eure Strings zu terminieren und eure Variablen zu initialisieren!";
    char urls[10][150] = {
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "https://ilias.hhu.de/ilias.php?ref_id=1&cmdClass=ilrepositorygui&cmdNode=va&baseClass=ilrepositorygui",
        "https://en.wikipedia.org/wiki/C_(programming_language)",
        "https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DVhh_GeBPOhs&format=json",
        "https://i.imgur.com/pbqiLgY.gif",
        "https://raw.githubusercontent.com/ProjectDock/programming-memes/main/src/MEMES/images/I-am-Harshdeep/meme.png",
        "https://abstrusegoose.com/strips/you_down_wit_OPC-yeah_you_know_me.png",
        "https://i.imgur.com/5DlqfCl.jpg",
        "https://devhumor.com/content/uploads/images/December2016/c++-c-class.jpg",
        "https://i.imgur.com/cV9m29E.png",
    };
    urls_testen(urls, 10, text);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, keine_urls);
    tcase_add_test(tc1_1, beispiel);
    tcase_add_test(tc1_1, beispiel_in_text);
    tcase_add_test(tc1_1, alle_drei_formate);
    tcase_add_test(tc1_1, verbotene_sonderzeichen);
    tcase_add_test(tc1_1, erlaubte_sonderzeichen);
    tcase_add_test(tc1_1, www);
    tcase_add_test(tc1_1, nicht_ganz_https);
    tcase_add_test(tc1_1, verschiedene_urls);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
