/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "strings_verbinden_tests.ts" instead.
 */

#include <check.h>

#line 1 "strings_verbinden_tests.ts"
#include <string.h>
#include "strings_verbinden.h"

START_TEST(hello_world_zusammen_laenge)
{
#line 5
    char string0[] = " ,olleH";
    char string1[] = "!dlroW";
    char zusammen[14];

    strings_verbinden(zusammen, string0, string1);

    int laenge_zusammen = strlen(zusammen);

    ck_assert_int_eq(13, laenge_zusammen);

}
END_TEST

START_TEST(hello_world_nullterminator)
{
#line 16
    char string0[] = " ,olleH";
    char string1[] = "!dlroW";
    char zusammen[14];

    strings_verbinden(zusammen, string0, string1);

    char nullterminator = zusammen[13];

    ck_assert_int_eq('\0', nullterminator);

}
END_TEST

START_TEST(hello_world_zusammen)
{
#line 27
    char string0[] = " ,olleH";
    char string1[] = "!dlroW";
    char zusammen[14];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "Hello, World!");

}
END_TEST

START_TEST(hello_leer_zusammen)
{
#line 36
    char string0[] = "olleH";
    char string1[] = "";
    char zusammen[6];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "Hello");

}
END_TEST

START_TEST(leer_world_zusammen)
{
#line 45
    char string0[] = "";
    char string1[] = "dlroW";
    char zusammen[6];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "World");

}
END_TEST

START_TEST(leer_leer_zusammen)
{
#line 54
    char string0[] = "";
    char string1[] = "";
    char zusammen[1];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "");

}
END_TEST

START_TEST(aaaaaaaa)
{
#line 63
    char string0[] = "aaaa";
    char string1[] = "aaaa";
    char zusammen[9];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "aaaaaaaa");

}
END_TEST

START_TEST(lang_lang_zusammen)
{
#line 72
    char string0[] = " gnirtS regnaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaL";
    char string1[] = ".gnirtS regnaaaaaaaaaaaaaaaaaaaaaaaaaaaal nie hcon dnu";
    char zusammen[107];

    strings_verbinden(zusammen, string0, string1);

    ck_assert_str_eq(zusammen, "Laaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanger String und noch ein laaaaaaaaaaaaaaaaaaaaaaaaaaaanger String.");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, hello_world_zusammen_laenge);
    tcase_add_test(tc1_1, hello_world_nullterminator);
    tcase_add_test(tc1_1, hello_world_zusammen);
    tcase_add_test(tc1_1, hello_leer_zusammen);
    tcase_add_test(tc1_1, leer_world_zusammen);
    tcase_add_test(tc1_1, leer_leer_zusammen);
    tcase_add_test(tc1_1, aaaaaaaa);
    tcase_add_test(tc1_1, lang_lang_zusammen);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
