/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "datum_tests.ts" instead.
 */

#include <check.h>

#line 1 "datum_tests.ts"
#include "datum.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void datum_pruefen(int jahr, int monat, int tag, char *erwartet){
    // Dieser Test schreibt ein Datum in eine Datei, um es danach
    // auszulesen und zu vergleichen.

    // Zufälligen Dateinamen generieren, damit niemand versucht, die
    // Datei selber zu öffnen.
    char dateiname[100];
    snprintf(dateiname, sizeof(dateiname), "datum_%i.txt", rand());

    // Datei öffnen.
    FILE *datei = fopen(dateiname, "w");
    // Datum erstellen.
    datum ein_datum = neues_datum(jahr, monat, tag);

    // Datum in eine Datei schreiben.
    datum_ausgeben(ein_datum, datei);

    // Prüfen, ob Datei von Student geschlossen wurde.
    int error = fseek(datei, 0, SEEK_SET);
    if (error){
        printf(
            "FEHLER: Die Datei darf nicht geschlossen werden. "
            "Wahrscheinlich will der Benutzer der Funktion noch mehr "
            "in die Datei schreiben, als nur ein Datum. Das aufrufende "
            "Programm schliesst die Datei bereits. Eine Datei darf "
            "nicht doppelt geschlossen werden.\n"
        );
        remove(dateiname);
        exit(1);
    }
    fclose(datei);

    // Datum aus Datei lesen und vergleichen.
    datei = fopen(dateiname, "r");

    // Null-Initialisierten Speicher anlegen.
    char datum_text[100 + 1];
    memset(datum_text, 0, sizeof(datum_text));

    // Bis zu 100 Zeichen lesen
    int n = fread(datum_text, 1, 100, datei);

    // Aufräumen.
    fclose(datei);
    remove(dateiname);

    if (n >= 0){
        printf("Ausgegebenes datum: \"%s\"\n", datum_text);
    }

    if (n != 10){
        printf("FEHLER: Datum muss genau 10 Zeichen lang sein\n");
    }
    ck_assert_int_eq(n, 10);

    ck_assert_str_eq(datum_text, erwartet);
}

START_TEST(datum_ist_gleich)
{
#line 65
    datum a = neues_datum(2020, 12, 24);
    datum b = neues_datum(2020, 12, 24);
    ck_assert_int_eq(datum_vergleichen(a, b), 0);
    ck_assert_int_eq(datum_vergleichen(b, a), 0);

}
END_TEST

START_TEST(datum_ist_davor)
{
#line 71
    datum a = neues_datum(2019, 11, 1);
    datum b = neues_datum(2020, 12, 2);
    ck_assert_int_lt(datum_vergleichen(a, b), 0);
    ck_assert_int_gt(datum_vergleichen(b, a), 0);

}
END_TEST

START_TEST(datum_ist_danach)
{
#line 77
    datum a = neues_datum(2020, 12, 1);
    datum b = neues_datum(2020, 11, 1);
    ck_assert_int_gt(datum_vergleichen(a, b), 0);
    ck_assert_int_lt(datum_vergleichen(b, a), 0);

}
END_TEST

START_TEST(datum_ist_davor_gleiches_jahr)
{
#line 83
    datum a = neues_datum(2020, 1, 30);
    datum b = neues_datum(2020, 2, 30);
    ck_assert_int_lt(datum_vergleichen(a, b), 0);
    ck_assert_int_gt(datum_vergleichen(b, a), 0);

}
END_TEST

START_TEST(datum_ist_davor_gleicher_monat_gleiches_jahr)
{
#line 89
    datum a = neues_datum(2020, 8, 30);
    datum b = neues_datum(2020, 8, 31);
    ck_assert_int_lt(datum_vergleichen(a, b), 0);
    ck_assert_int_gt(datum_vergleichen(b, a), 0);

}
END_TEST

START_TEST(datum_ausgabe_zweistellig)
{
#line 95
    datum_pruefen(2020, 12, 30, "2020-12-30");

}
END_TEST

START_TEST(datum_ausgabe_einstelliger_monat_und_tag)
{
#line 98
    datum_pruefen(1970, 1, 1, "1970-01-01");

}
END_TEST

START_TEST(datum_ausgabe_einstelliges_jahr)
{
#line 101
    datum_pruefen(1, 10, 20, "0001-10-20");

}
END_TEST

START_TEST(datum_ausgabe_zweistelliges_jahr)
{
#line 104
    datum_pruefen(99, 10, 1, "0099-10-01");

}
END_TEST

START_TEST(datum_ausgabe_dreistelliges_jahr)
{
#line 107
    datum_pruefen(123, 3, 14, "0123-03-14");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, datum_ist_gleich);
    tcase_add_test(tc1_1, datum_ist_davor);
    tcase_add_test(tc1_1, datum_ist_danach);
    tcase_add_test(tc1_1, datum_ist_davor_gleiches_jahr);
    tcase_add_test(tc1_1, datum_ist_davor_gleicher_monat_gleiches_jahr);
    tcase_add_test(tc1_1, datum_ausgabe_zweistellig);
    tcase_add_test(tc1_1, datum_ausgabe_einstelliger_monat_und_tag);
    tcase_add_test(tc1_1, datum_ausgabe_einstelliges_jahr);
    tcase_add_test(tc1_1, datum_ausgabe_zweistelliges_jahr);
    tcase_add_test(tc1_1, datum_ausgabe_dreistelliges_jahr);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
