all:
	gcc -g -fsanitize=address -fsanitize=undefined -Wall -std=c99 roulette.c -o exe && ./exe > result.txt
enter:
	gcc -g -fsanitize=address -fsanitize=undefined -Wall -std=c99 roulette.c -o exe && ./exe > result.txt
