/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "simple_string_tests.ts" instead.
 */

#include <check.h>

#line 1 "simple_string_tests.ts"
#include "simple_string.h"

START_TEST(laenge_leerer_string)
{
#line 4
    char *string = "";
    int anzahl = zeichen_zaehlen(string);
    ck_assert_int_eq(0, anzahl);

}
END_TEST

START_TEST(laenge_ente)
{
#line 9
    char *string = "Ente";
    int anzahl = zeichen_zaehlen(string);
    ck_assert_int_eq(4, anzahl);

}
END_TEST

START_TEST(laenge_hallo)
{
#line 14
    char *string = "Hallo, Welt!";
    int anzahl = zeichen_zaehlen(string);
    ck_assert_int_eq(12, anzahl);


}
END_TEST

START_TEST(laenge_langer_string)
{
#line 20
    char *string =
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789";
    int anzahl = zeichen_zaehlen(string);
    ck_assert_int_eq(500, anzahl);

}
END_TEST

START_TEST(leeren_string_kopieren)
{
#line 35
    char ziel[25];
    for (int i = 0; i < 25; i++){
        ziel[i] = '?';
    }
    char *quelle = "";

    string_kopieren(ziel, quelle);

    ck_assert_str_eq(ziel, quelle);

}
END_TEST

START_TEST(ente_kopieren)
{
#line 46
    char ziel[25];
    for (int i = 0; i < 25; i++){
        ziel[i] = '?';
    }
    char *quelle = "Hier kommt die Ente.";

    string_kopieren(ziel, quelle);

    ck_assert_str_eq(ziel, quelle);

}
END_TEST

START_TEST(langen_string_kopieren)
{
#line 57
    char ziel[101];
    for (int i = 0; i < 101; i++){
        ziel[i] = '?';
    }
    char *quelle =
        "01234567890123456789012345678901234567890123456789"
        "01234567890123456789012345678901234567890123456789";

    string_kopieren(ziel, quelle);

    ck_assert_str_eq(ziel, quelle);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, laenge_leerer_string);
    tcase_add_test(tc1_1, laenge_ente);
    tcase_add_test(tc1_1, laenge_hallo);
    tcase_add_test(tc1_1, laenge_langer_string);
    tcase_add_test(tc1_1, leeren_string_kopieren);
    tcase_add_test(tc1_1, ente_kopieren);
    tcase_add_test(tc1_1, langen_string_kopieren);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
