/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "strings_ersetzen_tests.ts" instead.
 */

#include <check.h>

#line 1 "strings_ersetzen_tests.ts"
#include "strings_ersetzen.h"

void strings_testen(
    char *text,
    char *richtige_ausgabe,
    char strings[100][100],
    char richtige_strings[100][100],
    int richtige_anzahl_strings
){
    char ausgabe[1000];
    int anzahl_strings = strings_ersetzen(ausgabe, text, strings);

    ck_assert_str_eq(ausgabe, richtige_ausgabe);

    ck_assert_int_eq(anzahl_strings, richtige_anzahl_strings);

    for (int i = 0; i < anzahl_strings; i++){
        ck_assert_str_eq(strings[i], richtige_strings[i]);
    }
}

START_TEST(keine_stings)
{
#line 23
    char strings[100][100];
    char richtige_strings[100][100];
    strings_testen(
        "Hello, World!",
        "Hello, World!",
        strings,
        richtige_strings,
        0);

}
END_TEST

START_TEST(einzelne_sternchen)
{
#line 33
    char strings[100][100] = {"Hello", "World"};
    char richtige_strings[100][100] = {"*", "*"};
    strings_testen(
        "*, *!",
        "Hello, World!",
        strings,
        richtige_strings,
        2);

}
END_TEST

START_TEST(mehrere_sternchen)
{
#line 43
    char strings[100][100] = {"Thank"};
    char richtige_strings[100][100] = {"****"};
    strings_testen(
        "**** you!",
        "Thank you!",
        strings,
        richtige_strings,
        1);

}
END_TEST

START_TEST(schinken)
{
#line 53
    char strings[100][100] = {"Ohrwurm", "belegtes Brot", "Schinken"};
    char richtige_strings[100][100] = {"*", "***", "********"};
    strings_testen(
        "Was hilft gegen einen *? - Ein *** mit ********!",
        "Was hilft gegen einen Ohrwurm? - Ein belegtes Brot mit Schinken!",
        strings,
        richtige_strings,
        3);

}
END_TEST

START_TEST(bestes_video)
{
#line 63
    char strings[100][100] = {
        "https",
        "www",
        "youtube",
        "com",
        "watch",
        "v",
        "dQw4w9WgXcQ",
    };
    char richtige_strings[100][100] = {
        "***",
        "***",
        "**",
        "*",
        "*",
        "*******",
        "*",
    };
    strings_testen(
        "***://***.**.*/*?*******=*",
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        strings,
        richtige_strings,
        7);

}
END_TEST

START_TEST(code_kommentieren)
{
#line 89
    char strings[100][100] = {
        "githubusercontent",
        "ProjectDock",
        "memes",
        "png",
    };
    char richtige_strings[100][100] = {
        "*",
        "**",
        "*",
        "***************************",
    };
    strings_testen(
        "https://raw.*.com/**/programming-*/"
        "main/src/MEMES/images/I-am-Harshdeep/meme.***************************",
        "https://raw.githubusercontent.com/ProjectDock/programming-memes/"
        "main/src/MEMES/images/I-am-Harshdeep/meme.png",
        strings,
        richtige_strings,
        4);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, keine_stings);
    tcase_add_test(tc1_1, einzelne_sternchen);
    tcase_add_test(tc1_1, mehrere_sternchen);
    tcase_add_test(tc1_1, schinken);
    tcase_add_test(tc1_1, bestes_video);
    tcase_add_test(tc1_1, code_kommentieren);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
