/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tiere_zaehlen_tests.ts" instead.
 */

#include <check.h>

#line 1 "tiere_zaehlen_tests.ts"
#include "tiere_zaehlen.h" 			 

START_TEST(leerer_text)
{
#line 4
    char *text = "";
    char tiere[10][16] = {"In", "diesem", "Array", "steht", "nur", "Quatsch"};
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 0);

}
END_TEST

START_TEST(keine_tiere)
{
#line 10
    char *text = "Bus Auto Bahn Kugelschreiber";
    char tiere[10][16];
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 0);

}
END_TEST

START_TEST(eine_ente)
{
#line 16
    char *text = "Ente";
    char tiere[10][16];
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 1);
    ck_assert_str_eq(tiere[0], "Ente");

}
END_TEST

START_TEST(zwei_enten)
{
#line 23
    char *text = "Ente Ente";
    char tiere[10][16];
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 2);
    char *erwartere_tiere[] = {"Ente", "Ente"};
    for (int i = 0; i < 2; i++){
        ck_assert_str_eq(tiere[i], erwartere_tiere[i]);
    }

}
END_TEST

START_TEST(ente_ente_ente_gans)
{
#line 33
    char *text = "Ente Ente Ente Gans";
    char tiere[10][16];
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 4);
    char *erwartere_tiere[] = {"Ente", "Ente", "Ente", "Gans"};
    for (int i = 0; i < 4; i++){
        ck_assert_str_eq(tiere[i], erwartere_tiere[i]);
    }

}
END_TEST

START_TEST(versteckte_tiere)
{
#line 43
    char *text = "0123456789Ente_Maus Ente{}[]\r\n\t\"'~#.:,;/*-+Auto<>|Saigaantilope!$&%/()==?Gans462435Nasenaffe62w435235Nasenaffe7263456345";
    char *erwartere_tiere[] = {"Ente", "Maus", "Ente", "Saigaantilope", "Gans", "Nasenaffe", "Nasenaffe"};
    char tiere[10][16];
    int anzahl_tiere = tiere_zaehlen(tiere, text);
    ck_assert_int_eq(anzahl_tiere, 7);
    for (int i = 0; i < 7; i++){
        ck_assert_str_eq(tiere[i], erwartere_tiere[i]);
    }
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, leerer_text);
    tcase_add_test(tc1_1, keine_tiere);
    tcase_add_test(tc1_1, eine_ente);
    tcase_add_test(tc1_1, zwei_enten);
    tcase_add_test(tc1_1, ente_ente_ente_gans);
    tcase_add_test(tc1_1, versteckte_tiere);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
