/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "caesar_plus2_klein_tests.ts" instead.
 */

#include <check.h>

#line 1 "caesar_plus2_klein_tests.ts"
#include "caesar_plus2_klein.h"

START_TEST(caesar_c_to_e)
{
#line 4
    char to_test[] = "c";
    caesar(to_test);

    char res[] = "e";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_y_to_a)
{
#line 12
    char to_test[] = "y";
    caesar(to_test);

    char res[] = "a";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_z_to_b)
{
#line 20
    char to_test[] = "z";
    caesar(to_test);

    char res[] = "b";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_longer_string)
{
#line 28
    char to_test[] ="diesisteinlangerstring";
    caesar(to_test);

    char res[] = "fkgukuvgkpncpigtuvtkpi";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_really_long_string)
{
#line 36
    char to_test[] ="abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz";
    caesar(to_test);

    char res[] = "cdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(encode_and_compare_true_short)
{
#line 44
    char string_to_encode[] = "y";
    char clearstring[] = "a";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 1);


}
END_TEST

START_TEST(encode_and_compare_true_long)
{
#line 50
    char string_to_encode[] = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz";
    char clearstring[] = "cdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 1);


}
END_TEST

START_TEST(encode_and_compare_false)
{
#line 56
    char string_to_encode[] = "a";
    char clearstring[] = "a";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, caesar_c_to_e);
    tcase_add_test(tc1_1, caesar_y_to_a);
    tcase_add_test(tc1_1, caesar_z_to_b);
    tcase_add_test(tc1_1, caesar_longer_string);
    tcase_add_test(tc1_1, caesar_really_long_string);
    tcase_add_test(tc1_1, encode_and_compare_true_short);
    tcase_add_test(tc1_1, encode_and_compare_true_long);
    tcase_add_test(tc1_1, encode_and_compare_false);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
