/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "simpleString_tests.ts" instead.
 */

#include <check.h>

#line 1 "simpleString_tests.ts"
/*
 * 1) Studis sollen nach dieser Aufgabe
 *  - Tests von einer ts Dateie in eine c-Datei umwandeln können.
 *    (Sie müssen das '>' noch nicht verstehen.)
 *  - die resultierenden Dateien kompilieren und ausführen können.
 *  - verstehen, was die Ausgaben bedeuten.
 * 2) Beispiele für Fragen an die Studis, um das Verständnis zu prüfen:
 *  - Was bedeutet die Zeile  "0%: Checks: 1, Failures: 1, Errors: 0" ?
 *  - Welche Tests schlagen fehl?
 */

// checkmk simpleString_tests.ts > simpleString_tests.c
// gcc simpleString_korrigiert.c simpleString_tests.c -o tests -Wall -lsubunit -lm -lpthread -lrt -lcheck -std=c99 -g -fprofile-arcs -ftest-coverage

#include <string.h>
#include "simpleString.h"

START_TEST(char_is_in_string)
{
#line 19
    char *haystack = "a";
    char needle = 'a';
    int result = count_in_string(haystack, needle);
    ck_assert_int_eq(1, result);

}
END_TEST

START_TEST(char_is_two_times_in_string)
{
#line 25
    char *haystack = "aba";
    char needle = 'a';
    int result = count_in_string(haystack, needle);
    ck_assert_int_eq(2, result);

}
END_TEST

START_TEST(not_same_length)
{
#line 31
    char *string1="abc";
    char *string2="abcd";
    int result = my_strcmp(string1, string2);
    ck_assert_int_eq(0, result);

}
END_TEST

START_TEST(same_length_different_strings)
{
#line 37
    char *string1="abc";
    char *string2="abd";
    int result = my_strcmp(string1, string2);
    ck_assert_int_eq(0, result);

}
END_TEST

START_TEST(same_strings)
{
#line 43
    char *string1="abc";
    char *string2="abc";
    int result = my_strcmp(string1, string2);
    ck_assert_int_eq(1, result);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, char_is_in_string);
    tcase_add_test(tc1_1, char_is_two_times_in_string);
    tcase_add_test(tc1_1, not_same_length);
    tcase_add_test(tc1_1, same_length_different_strings);
    tcase_add_test(tc1_1, same_strings);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
